### ISSUE TITLE
Your class could not parse this

### ISSUE THREAD

**Issue by sarbull** [JonathanFrias/PHP-Database-Helper#1]
Using $db = new MysqliDb(); $db->rawQuery($query);

```
  SELECT 
    post.id          AS id, 
    post.post_title  AS name,
    pm.meta_value    AS price,
    p2.guid          AS image
  FROM w6p_posts AS post
  LEFT JOIN w6p_postmeta AS pm ON pm.post_id=post.id AND pm.meta_key='_regular_price'
  LEFT JOIN w6p_posts as p2 ON p2.post_parent=post.id AND p2.post_type='attachment'
  WHERE post.post_type='product'
  GROUP by post.id;
```

You are welcome.

**Comment by JonathanFrias** [comment]
Thanks, I don't know why it wouldn't. It literally passes the provided query on. 

If you're having problems, you can fork this project and work on it yourself. I'm not really maintaining it anymore.

This was a just a project I did for fun. 
If you are doing serious work, and need an ORM I would recommend: Eloquent
 http://www.edzynda.com/use-laravels-eloquent-orm-outside-of-laravel/

Or just use the full laravel stack: laravel.com

**Comment by sarbull** [comment]
Thanks! I'ved implemented php-activerecord for my onda-mvc thanks to the fact that your class failed. Anyway, good job!
